--- #YAML:1.0
name:               Daemon-Mplayer
version:            0.010
abstract:           Daemonize mplayer
author:
    - Magnus Woldrich <trapd00r@trapd00r.se>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
resources:
    bugtracker:  https://github.com/trapd00r/Daemon-Mplayer/issues
    repository:  https://github.com/trapd00r/Daemon-Mplayer
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
